In [1]:
from pathlib import Path

import pandas as pd

DATA_PATH = Path("..") / "data" / "nba_player_stats.csv"

df = pd.read_csv(DATA_PATH)

print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"Seasons: {df['year_id'].nunique()} ({df['year_id'].min()} → {df['year_id'].max()})")
print(f"Players: {df['player_name'].nunique():,}")
print(f"Teams:   {df['team_name_abbr'].nunique()}")
print()

display(df.dtypes.to_frame("dtype"))
display(df.isna().sum().to_frame("nulls").assign(pct=lambda x: (x["nulls"] / len(df) * 100).round(1)))
display(df.describe())
display(df.head(10))

Shape: 36,469 rows × 12 columns
Seasons: 80 (1946-47 → 2025-26)
Players: 5,370
Teams:   139

                  dtype
player_name      object
player_url       object
year_id          object
age             float64
team_name_abbr   object
games           float64
mp              float64
per             float64
bpm             float64
vorp            float64
ws              float64
ws_per_48       float64

                nulls   pct
player_name         0   0.0
player_url          6   0.0
year_id             0   0.0
age              3086   8.5
team_name_abbr      0   0.0
games            3065   8.4
mp               4148  11.4
per              4165  11.4
bpm              8746  24.0
vorp             8741  24.0
ws               3076   8.4
ws_per_48        4165  11.4

,age,games,mp,per,bpm,vorp,ws,ws_per_48
count,33383.000000,33404.000000,32321.000000,32304.000000,27723.000000,27728.000000,33393.000000,32304.000000
mean,26.461822,48.434499,1150.425451,12.516948,-1.852639,0.536497,2.347046,0.066351
std,3.859351,26.601867,922.187082,6.240924,4.882482,1.249516,2.944688,0.103742
min,18.000000,1.000000,0.000000,-90.600000,-92.100000,-2.600000,-2.800000,-2.519000
25%,24.000000,24.000000,306.000000,9.800000,-3.600000,-0.100000,0.200000,0.031000
50%,26.000000,53.000000,975.000000,12.700000,-1.500000,0.100000,1.300000,0.076000
75%,29.000000,73.000000,1872.000000,15.700000,0.400000,0.800000,3.600000,0.116000
max,46.000000,90.000000,3882.000000,133.800000,242.200000,12.500000,25.400000,2.712000

,player_name,player_url,year_id,age,team_name_abbr,games,mp,per,bpm,vorp,ws,ws_per_48
0,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1990-91,22.0,POR,43.0,290.0,13.1,-4.6,-0.2,0.5,0.079
1,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1991-92,23.0,POR,71.0,934.0,13.5,-2.6,-0.1,2.1,0.110
2,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,2TM,75.0,1311.0,13.2,-3.9,-0.6,2.0,0.074
3,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,MIL,12.0,159.0,11.9,-3.5,-0.1,0.1,0.035
4,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,BOS,63.0,1152.0,13.4,-4.0,-0.6,1.9,0.079
5,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1993-94,25.0,BOS,13.0,159.0,9.2,-7.4,-0.2,-0.1,-0.032
6,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,2TM,54.0,506.0,12.6,-4.3,-0.3,0.3,0.027
7,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,SAC,51.0,476.0,14.1,-3.1,-0.1,0.6,0.058
8,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,PHI,3.0,30.0,-12.5,-24.9,-0.2,-0.3,-0.466
9,Zaid Abdul-Aziz,https://www.basketball-reference.com/players/a...,1968-69,22.0,2TM,49.0,945.0,12.3,NaN,NaN,-0.3,-0.016

In [2]:
null_url = df[df["player_url"].isna()]

print(f"Rows with null player_url: {len(null_url)}")
print(f"Unique players: {null_url['player_name'].nunique()}")
print()
display(null_url)

Rows with null player_url: 6
Unique players: 3

,player_name,player_url,year_id,age,team_name_abbr,games,mp,per,bpm,vorp,ws,ws_per_48
24901,William Smith,NaN,1971-72,22.0,POR,22.0,448.0,10.8,NaN,NaN,0.0,-0.003
24902,William Smith,NaN,1972-73,23.0,POR,8.0,43.0,15.5,NaN,NaN,0.2,0.199
29009,Jeenathan Williams,NaN,2022-23,23.0,POR,5.0,127.0,15.5,-3.0,0.0,0.3,0.120
29010,Jeenathan Williams,NaN,2023-24,24.0,HOU,22.0,129.0,15.6,-1.6,0.0,0.3,0.110
29011,Jeenathan Williams,NaN,2024-25,25.0,HOU,20.0,147.0,8.6,-5.7,-0.1,0.0,-0.007
29385,Jim Wilson,NaN,1970-71,NaN,PTC,6.0,44.0,1.7,NaN,NaN,-0.1,-0.060

In [3]:
missing_urls = {
    "William Smith": "https://www.basketball-reference.com/players/s/smithwi01.html",
    "Jeenathan Williams": "https://www.basketball-reference.com/players/w/willije02.html",
    "Jim Wilson": "https://www.basketball-reference.com/players/w/wilsoji01.html",
}

df["player_url"] = df["player_url"].fillna(df["player_name"].map(missing_urls))

print(f"Remaining null player_url: {df['player_url'].isna().sum()}")
display(df[df["player_name"].isin(missing_urls)][["player_name", "player_url", "year_id"]].drop_duplicates())

Remaining null player_url: 0

,player_name,player_url,year_id
24901,William Smith,https://www.basketball-reference.com/players/s...,1971-72
24902,William Smith,https://www.basketball-reference.com/players/s...,1972-73
29009,Jeenathan Williams,https://www.basketball-reference.com/players/w...,2022-23
29010,Jeenathan Williams,https://www.basketball-reference.com/players/w...,2023-24
29011,Jeenathan Williams,https://www.basketball-reference.com/players/w...,2024-25
29385,Jim Wilson,https://www.basketball-reference.com/players/w...,1970-71

In [4]:
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"Seasons: {df['year_id'].nunique()} ({df['year_id'].min()} → {df['year_id'].max()})")
print(f"Players: {df['player_name'].nunique():,}")
print(f"Teams:   {df['team_name_abbr'].nunique()}")
print()

display(df.dtypes.to_frame("dtype"))
display(df.isna().sum().to_frame("nulls").assign(pct=lambda x: (x["nulls"] / len(df) * 100).round(1)))
display(df.describe())
display(df.head(10))

Shape: 36,469 rows × 12 columns
Seasons: 80 (1946-47 → 2025-26)
Players: 5,370
Teams:   139

                  dtype
player_name      object
player_url       object
year_id          object
age             float64
team_name_abbr   object
games           float64
mp              float64
per             float64
bpm             float64
vorp            float64
ws              float64
ws_per_48       float64

                nulls   pct
player_name         0   0.0
player_url          0   0.0
year_id             0   0.0
age              3086   8.5
team_name_abbr      0   0.0
games            3065   8.4
mp               4148  11.4
per              4165  11.4
bpm              8746  24.0
vorp             8741  24.0
ws               3076   8.4
ws_per_48        4165  11.4

,age,games,mp,per,bpm,vorp,ws,ws_per_48
count,33383.000000,33404.000000,32321.000000,32304.000000,27723.000000,27728.000000,33393.000000,32304.000000
mean,26.461822,48.434499,1150.425451,12.516948,-1.852639,0.536497,2.347046,0.066351
std,3.859351,26.601867,922.187082,6.240924,4.882482,1.249516,2.944688,0.103742
min,18.000000,1.000000,0.000000,-90.600000,-92.100000,-2.600000,-2.800000,-2.519000
25%,24.000000,24.000000,306.000000,9.800000,-3.600000,-0.100000,0.200000,0.031000
50%,26.000000,53.000000,975.000000,12.700000,-1.500000,0.100000,1.300000,0.076000
75%,29.000000,73.000000,1872.000000,15.700000,0.400000,0.800000,3.600000,0.116000
max,46.000000,90.000000,3882.000000,133.800000,242.200000,12.500000,25.400000,2.712000

,player_name,player_url,year_id,age,team_name_abbr,games,mp,per,bpm,vorp,ws,ws_per_48
0,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1990-91,22.0,POR,43.0,290.0,13.1,-4.6,-0.2,0.5,0.079
1,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1991-92,23.0,POR,71.0,934.0,13.5,-2.6,-0.1,2.1,0.110
2,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,2TM,75.0,1311.0,13.2,-3.9,-0.6,2.0,0.074
3,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,MIL,12.0,159.0,11.9,-3.5,-0.1,0.1,0.035
4,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,BOS,63.0,1152.0,13.4,-4.0,-0.6,1.9,0.079
5,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1993-94,25.0,BOS,13.0,159.0,9.2,-7.4,-0.2,-0.1,-0.032
6,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,2TM,54.0,506.0,12.6,-4.3,-0.3,0.3,0.027
7,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,SAC,51.0,476.0,14.1,-3.1,-0.1,0.6,0.058
8,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,PHI,3.0,30.0,-12.5,-24.9,-0.2,-0.3,-0.466
9,Zaid Abdul-Aziz,https://www.basketball-reference.com/players/a...,1968-69,22.0,2TM,49.0,945.0,12.3,NaN,NaN,-0.3,-0.016

In [5]:
null_age = df[df["age"].isna()]

print(f"Rows with null age: {len(null_age):,}")
print(f"Unique players: {null_age['player_name'].nunique():,}")
print()

# Many null-age rows look like non-playing seasons (reason stored in team_name_abbr)
did_not_play = null_age["team_name_abbr"].str.startswith("Did not play", na=False)
print("team_name_abbr breakdown among null-age rows:")
display(null_age["team_name_abbr"].value_counts().head(20).to_frame("rows"))
print(f"\nDid not play: {did_not_play.sum():,} ({did_not_play.mean():.1%})")
print(f"Actual team seasons with null age: {(~did_not_play).sum():,}")
print()

print("Null rates among null-age rows:")
display(null_age.isna().mean().mul(100).round(1).to_frame("pct_null"))

print("\nNull-age rows that look like real team seasons:")
display(null_age.loc[~did_not_play].head(20))

Rows with null age: 3,086
Unique players: 1,482

team_name_abbr breakdown among null-age rows:

                                      rows
team_name_abbr
Did not play - other pro league       2327
Did not play - injury                  250
Did not play - military service        116
Did not play - waived                   83
Did not play - retired                  70
Did not play - other                    63
Did not play - unsigned                 38
Did not play - suspended                35
Did not play - illness                  20
Did not play -                          12
Did not play - minor league baseball     7
Did not play - legal                     7
Did not play - major league baseball     6
Did not play - contract dispute          5
ANA                                      4
DNR                                      4
Did not play - rehab                     3
Did not play - contractual issues        2
Did not play - Rhodes Scholar            2
2TM                                      2

Did not play: 3,065 (99.3%)
Actual team seasons with null age: 21

Null rates among null-age rows:

                pct_null
player_name          0.0
player_url           0.0
year_id              0.0
age                100.0
team_name_abbr       0.0
games               99.3
mp                  99.3
per                 99.3
bpm                100.0
vorp               100.0
ws                  99.3
ws_per_48           99.3

Null-age rows that look like real team seasons:

,player_name,player_url,year_id,age,team_name_abbr,games,mp,per,bpm,vorp,ws,ws_per_48
365,Bill Allen,https://www.basketball-reference.com/players/a...,1967-68,NaN,ANA,38.0,857.0,11.9,NaN,NaN,0.6,0.033
3353,Clarence Brookins,https://www.basketball-reference.com/players/b...,1970-71,NaN,FLO,8.0,59.0,7.7,NaN,NaN,-0.2,-0.153
4043,Walt Byrd,https://www.basketball-reference.com/players/b...,1969-70,NaN,MMF,22.0,109.0,2.3,NaN,NaN,-0.3,-0.123
10937,Darrell Hardy,https://www.basketball-reference.com/players/h...,1967-68,NaN,HSM,17.0,172.0,19.3,NaN,NaN,0.5,0.149
14704,Wilbur Kirkland,https://www.basketball-reference.com/players/k...,1969-70,NaN,PTP,2.0,27.0,6.6,NaN,NaN,0.0,0.023
15560,Dick Lee,https://www.basketball-reference.com/players/l...,1967-68,NaN,ANA,2.0,2.0,30.7,NaN,NaN,0.0,0.084
16237,R.B. Lynam,https://www.basketball-reference.com/players/l...,1967-68,NaN,DNR,7.0,39.0,-0.2,NaN,NaN,0.0,-0.011
18704,Richie Moore,https://www.basketball-reference.com/players/m...,1967-68,NaN,DNR,18.0,211.0,3.0,NaN,NaN,0.0,0.010
20489,Errol Palmer,https://www.basketball-reference.com/players/p...,1967-68,NaN,MNM,63.0,1191.0,17.2,NaN,NaN,4.2,0.168
20639,Charley Parks,https://www.basketball-reference.com/players/p...,1968-69,NaN,DNR,2.0,5.0,-10.8,NaN,NaN,0.0,-0.220
24836,Pete Smith,https://www.basketball-reference.com/players/s...,1972-73,NaN,SDA,5.0,32.0,-9.1,NaN,NaN,-0.2,-0.262
25496,Randy Stoll,https://www.basketball-reference.com/players/s...,1967-68,NaN,ANA,25.0,403.0,9.8,NaN,NaN,0.3,0.042
26272,Willis Thomas,https://www.basketball-reference.com/players/t...,1967-68,NaN,2TM,62.0,1067.0,12.2,NaN,NaN,1.5,0.066
26273,Willis Thomas,https://www.basketball-reference.com/players/t...,1967-68,NaN,DNR,24.0,542.0,13.2,NaN,NaN,0.8,0.075
26274,Willis Thomas,https://www.basketball-reference.com/players/t...,1967-68,NaN,ANA,38.0,525.0,11.3,NaN,NaN,0.6,0.058
28332,Dexter Westbrook,https://www.basketball-reference.com/players/w...,1967-68,NaN,2TM,12.0,127.0,7.0,NaN,NaN,0.3,0.119
28333,Dexter Westbrook,https://www.basketball-reference.com/players/w...,1967-68,NaN,NJA,7.0,59.0,13.5,NaN,NaN,0.3,0.270
28334,Dexter Westbrook,https://www.basketball-reference.com/players/w...,1967-68,NaN,PTP,5.0,68.0,1.3,NaN,NaN,0.0,-0.012
29385,Jim Wilson,https://www.basketball-reference.com/players/w...,1970-71,NaN,PTC,6.0,44.0,1.7,NaN,NaN,-0.1,-0.060
35679,Jimmy Wilson,https://www.basketball-reference.com/players/w...,1970-71,NaN,PTC,6.0,44.0,1.7,NaN,NaN,-0.1,-0.060

In [6]:
before = len(df)
dnp_mask = df["team_name_abbr"].str.startswith("Did not play", na=False)

df = df.loc[~dnp_mask].copy()

print(f"Dropped {before - len(df):,} 'Did not play' rows ({before:,} → {len(df):,})")

null_age = df[df["age"].isna()]
print(f"Remaining null age: {len(null_age):,} rows / {null_age['player_name'].nunique()} players")
display(null_age[["player_name", "year_id", "team_name_abbr", "age", "games", "mp", "per", "ws"]])

Dropped 3,065 'Did not play' rows (36,469 → 33,404)
Remaining null age: 21 rows / 17 players

,player_name,year_id,team_name_abbr,age,games,mp,per,ws
365,Bill Allen,1967-68,ANA,NaN,38.0,857.0,11.9,0.6
3353,Clarence Brookins,1970-71,FLO,NaN,8.0,59.0,7.7,-0.2
4043,Walt Byrd,1969-70,MMF,NaN,22.0,109.0,2.3,-0.3
10937,Darrell Hardy,1967-68,HSM,NaN,17.0,172.0,19.3,0.5
14704,Wilbur Kirkland,1969-70,PTP,NaN,2.0,27.0,6.6,0.0
15560,Dick Lee,1967-68,ANA,NaN,2.0,2.0,30.7,0.0
16237,R.B. Lynam,1967-68,DNR,NaN,7.0,39.0,-0.2,0.0
18704,Richie Moore,1967-68,DNR,NaN,18.0,211.0,3.0,0.0
20489,Errol Palmer,1967-68,MNM,NaN,63.0,1191.0,17.2,4.2
20639,Charley Parks,1968-69,DNR,NaN,2.0,5.0,-10.8,0.0
24836,Pete Smith,1972-73,SDA,NaN,5.0,32.0,-9.1,-0.2
25496,Randy Stoll,1967-68,ANA,NaN,25.0,403.0,9.8,0.3
26272,Willis Thomas,1967-68,2TM,NaN,62.0,1067.0,12.2,1.5
26273,Willis Thomas,1967-68,DNR,NaN,24.0,542.0,13.2,0.8
26274,Willis Thomas,1967-68,ANA,NaN,38.0,525.0,11.3,0.6
28332,Dexter Westbrook,1967-68,2TM,NaN,12.0,127.0,7.0,0.3
28333,Dexter Westbrook,1967-68,NJA,NaN,7.0,59.0,13.5,0.3
28334,Dexter Westbrook,1967-68,PTP,NaN,5.0,68.0,1.3,0.0
29385,Jim Wilson,1970-71,PTC,NaN,6.0,44.0,1.7,-0.1
35679,Jimmy Wilson,1970-71,PTC,NaN,6.0,44.0,1.7,-0.1
36460,Bobby Wilson,1967-68,DLC,NaN,69.0,1562.0,10.4,0.6

In [7]:
before = len(df)
df = df.dropna(subset=["age"]).copy()

print(f"Dropped {before - len(df):,} rows with null age ({before:,} → {len(df):,})")
print(f"Remaining null age: {df['age'].isna().sum()}")

Dropped 21 rows with null age (33,404 → 33,383)
Remaining null age: 0

In [8]:
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"Seasons: {df['year_id'].nunique()} ({df['year_id'].min()} → {df['year_id'].max()})")
print(f"Players: {df['player_name'].nunique():,}")
print(f"Teams:   {df['team_name_abbr'].nunique()}")
print()

display(df.dtypes.to_frame("dtype"))
display(df.isna().sum().to_frame("nulls").assign(pct=lambda x: (x["nulls"] / len(df) * 100).round(1)))
display(df.describe())
display(df.head(10))

Shape: 33,383 rows × 12 columns
Seasons: 80 (1946-47 → 2025-26)
Players: 5,354
Teams:   108

                  dtype
player_name      object
player_url       object
year_id          object
age             float64
team_name_abbr   object
games           float64
mp              float64
per             float64
bpm             float64
vorp            float64
ws              float64
ws_per_48       float64

                nulls   pct
player_name         0   0.0
player_url          0   0.0
year_id             0   0.0
age                 0   0.0
team_name_abbr      0   0.0
games               0   0.0
mp               1083   3.2
per              1100   3.3
bpm              5660  17.0
vorp             5655  16.9
ws                 11   0.0
ws_per_48        1100   3.3

,age,games,mp,per,bpm,vorp,ws,ws_per_48
count,33383.000000,33383.000000,32300.000000,32283.000000,27723.000000,27728.000000,33372.000000,32283.000000
mean,26.461822,48.451847,1150.952198,12.520113,-1.852639,0.536497,2.348259,0.066387
std,3.859351,26.596132,922.185615,6.237418,4.882482,1.249516,2.945122,0.103718
min,18.000000,1.000000,0.000000,-90.600000,-92.100000,-2.600000,-2.800000,-2.519000
25%,24.000000,24.000000,307.000000,9.800000,-3.600000,-0.100000,0.200000,0.031000
50%,26.000000,53.000000,976.000000,12.700000,-1.500000,0.100000,1.300000,0.076000
75%,29.000000,73.000000,1873.000000,15.700000,0.400000,0.800000,3.600000,0.116000
max,46.000000,90.000000,3882.000000,133.800000,242.200000,12.500000,25.400000,2.712000

,player_name,player_url,year_id,age,team_name_abbr,games,mp,per,bpm,vorp,ws,ws_per_48
0,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1990-91,22.0,POR,43.0,290.0,13.1,-4.6,-0.2,0.5,0.079
1,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1991-92,23.0,POR,71.0,934.0,13.5,-2.6,-0.1,2.1,0.110
2,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,2TM,75.0,1311.0,13.2,-3.9,-0.6,2.0,0.074
3,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,MIL,12.0,159.0,11.9,-3.5,-0.1,0.1,0.035
4,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,BOS,63.0,1152.0,13.4,-4.0,-0.6,1.9,0.079
5,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1993-94,25.0,BOS,13.0,159.0,9.2,-7.4,-0.2,-0.1,-0.032
6,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,2TM,54.0,506.0,12.6,-4.3,-0.3,0.3,0.027
7,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,SAC,51.0,476.0,14.1,-3.1,-0.1,0.6,0.058
8,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,PHI,3.0,30.0,-12.5,-24.9,-0.2,-0.3,-0.466
9,Zaid Abdul-Aziz,https://www.basketball-reference.com/players/a...,1968-69,22.0,2TM,49.0,945.0,12.3,NaN,NaN,-0.3,-0.016

In [9]:
one_number_metrics = ["per", "bpm", "vorp", "ws", "ws_per_48"]

before = len(df)
missing_any = df[one_number_metrics].isna().any(axis=1)

print("Null counts before drop:")
display(df[one_number_metrics].isna().sum().to_frame("nulls"))

df = df.loc[~missing_any].copy()

print(f"Dropped {before - len(df):,} rows missing any one-number metric ({before:,} → {len(df):,})")
print(f"Seasons remaining: {df['year_id'].min()} → {df['year_id'].max()}")
print(f"Remaining nulls in metrics: {df[one_number_metrics].isna().sum().sum()}")

Null counts before drop:

           nulls
per         1100
bpm         5660
vorp        5655
ws            11
ws_per_48   1100

Dropped 5,660 rows missing any one-number metric (33,383 → 27,723)
Seasons remaining: 1973-74 → 2025-26
Remaining nulls in metrics: 0

In [10]:
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"Seasons: {df['year_id'].nunique()} ({df['year_id'].min()} → {df['year_id'].max()})")
print(f"Players: {df['player_name'].nunique():,}")
print(f"Teams:   {df['team_name_abbr'].nunique()}")
print()

display(df.dtypes.to_frame("dtype"))
display(df.isna().sum().to_frame("nulls").assign(pct=lambda x: (x["nulls"] / len(df) * 100).round(1)))
display(df.describe())
display(df.head(10))

Shape: 27,723 rows × 12 columns
Seasons: 53 (1973-74 → 2025-26)
Players: 4,184
Teams:   63

                  dtype
player_name      object
player_url       object
year_id          object
age             float64
team_name_abbr   object
games           float64
mp              float64
per             float64
bpm             float64
vorp            float64
ws              float64
ws_per_48       float64

                nulls  pct
player_name         0  0.0
player_url          0  0.0
year_id             0  0.0
age                 0  0.0
team_name_abbr      0  0.0
games               0  0.0
mp                  0  0.0
per                 0  0.0
bpm                 0  0.0
vorp                0  0.0
ws                  0  0.0
ws_per_48           0  0.0

,age,games,mp,per,bpm,vorp,ws,ws_per_48
count,27723.000000,27723.000000,27723.000000,27723.000000,27723.000000,27723.000000,27723.000000,27723.000000
mean,26.575803,48.009018,1118.809220,12.543282,-1.852639,0.536594,2.309014,0.067537
std,3.995016,26.664426,904.079205,6.265511,4.882482,1.249607,2.842593,0.102838
min,18.000000,1.000000,1.000000,-90.600000,-92.100000,-2.600000,-2.100000,-2.519000
25%,24.000000,24.000000,293.000000,9.800000,-3.600000,-0.100000,0.200000,0.033000
50%,26.000000,52.000000,937.000000,12.700000,-1.500000,0.100000,1.300000,0.077000
75%,29.000000,74.000000,1818.000000,15.700000,0.400000,0.800000,3.500000,0.116000
max,44.000000,90.000000,3638.000000,133.800000,242.200000,12.500000,21.200000,2.712000

,player_name,player_url,year_id,age,team_name_abbr,games,mp,per,bpm,vorp,ws,ws_per_48
0,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1990-91,22.0,POR,43.0,290.0,13.1,-4.6,-0.2,0.5,0.079
1,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1991-92,23.0,POR,71.0,934.0,13.5,-2.6,-0.1,2.1,0.110
2,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,2TM,75.0,1311.0,13.2,-3.9,-0.6,2.0,0.074
3,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,MIL,12.0,159.0,11.9,-3.5,-0.1,0.1,0.035
4,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,BOS,63.0,1152.0,13.4,-4.0,-0.6,1.9,0.079
5,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1993-94,25.0,BOS,13.0,159.0,9.2,-7.4,-0.2,-0.1,-0.032
6,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,2TM,54.0,506.0,12.6,-4.3,-0.3,0.3,0.027
7,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,SAC,51.0,476.0,14.1,-3.1,-0.1,0.6,0.058
8,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1994-95,26.0,PHI,3.0,30.0,-12.5,-24.9,-0.2,-0.3,-0.466
16,Zaid Abdul-Aziz,https://www.basketball-reference.com/players/a...,1973-74,27.0,HOU,79.0,2459.0,15.9,1.0,1.8,6.5,0.126

In [11]:
# Basketball-Reference already provides a season total row (2TM/3TM/…).
# Keep that aggregate and drop the per-team split rows for the same player-season.
ntm_pattern = r"^\d+TM$"
is_ntm = df["team_name_abbr"].str.match(ntm_pattern, na=False)
season_has_ntm = df.groupby(["player_url", "year_id"])["team_name_abbr"].transform(
    lambda s: s.str.match(ntm_pattern, na=False).any()
)

before = len(df)
df = df.loc[~season_has_ntm | is_ntm].copy()

n_ntm = df["team_name_abbr"].str.match(ntm_pattern, na=False).sum()
rows_per_season = df.groupby(["player_url", "year_id"]).size()
n_multi = (rows_per_season > 1).sum()

print(f"Merged multi-team seasons: dropped {before - len(df):,} team-split rows ({before:,} → {len(df):,})")
print(f"Remaining nTM total rows: {n_ntm:,}")
print(f"Player-seasons with >1 row left: {n_multi}")

Merged multi-team seasons: dropped 5,253 team-split rows (27,723 → 22,470)
Remaining nTM total rows: 2,539
Player-seasons with >1 row left: 17

In [12]:
# Exact scrape duplicates (e.g. Danté Exum) + alternate-name duplicates
# (Jeenathan Williams / Nate Williams share willije02).
before = len(df)

# Modern Nate Williams is Jeenathan; keep the BRef name for that URL.
jeenathan_url = "https://www.basketball-reference.com/players/w/willije02.html"
df.loc[df["player_url"] == jeenathan_url, "player_name"] = "Jeenathan Williams"

df = df.drop_duplicates()
df = df.drop_duplicates(subset=["player_url", "year_id"], keep="first").copy()

rows_per_season = df.groupby(["player_url", "year_id"]).size()
print(f"Dropped {before - len(df):,} duplicate player-season rows ({before:,} → {len(df):,})")
print(f"Player-seasons with >1 row left: {(rows_per_season > 1).sum()}")

Dropped 17 duplicate player-season rows (22,470 → 22,453)
Player-seasons with >1 row left: 0

In [13]:
# ABA existed 1967-68 → 1975-76; four teams joined the NBA for 1976-77.
# Drop ABA team seasons before the merger (keep contemporaneous NBA seasons).
ABA_TEAMS = {
    "ANA", "AND", "CAR", "DLC", "DNA", "DNR", "FLO", "HSM", "INA", "KEN", "LAS",
    "MMF", "MMS", "MMT", "MNM", "NJA", "NOB", "NYA", "OAK", "PTP", "PTC", "SAA",
    "SDA", "SDS", "SSL", "TEX", "UTS", "VIR",
}
MERGER_SEASON = "1976-77"

# nTM totals that include any ABA club (incl. rare NBA↔ABA swaps)
raw_pre = pd.read_csv(DATA_PATH)
raw_pre["player_url"] = raw_pre["player_url"].fillna(raw_pre["player_name"].map(missing_urls))
raw_pre = raw_pre.loc[
    (raw_pre["year_id"] < MERGER_SEASON)
    & ~raw_pre["team_name_abbr"].str.startswith("Did not play", na=False)
    & ~raw_pre["team_name_abbr"].str.match(r"^\d+TM$", na=False)
]
aba_season_keys = set(
    zip(
        raw_pre.loc[raw_pre["team_name_abbr"].isin(ABA_TEAMS), "player_url"],
        raw_pre.loc[raw_pre["team_name_abbr"].isin(ABA_TEAMS), "year_id"],
    )
)

pre_merger = df["year_id"] < MERGER_SEASON
is_aba_team = df["team_name_abbr"].isin(ABA_TEAMS)
is_ntm = df["team_name_abbr"].str.match(r"^\d+TM$", na=False)
ntm_touches_aba = [
    (url, year) in aba_season_keys
    for url, year in zip(df["player_url"], df["year_id"])
]
drop_aba = pre_merger & (is_aba_team | (is_ntm & pd.Series(ntm_touches_aba, index=df.index)))

before = len(df)
df = df.loc[~drop_aba].copy()

print(f"Dropped {before - len(df):,} pre-merger ABA rows ({before:,} → {len(df):,})")
print(f"Seasons remaining: {df['year_id'].min()} → {df['year_id'].max()}")
print(f"Pre-merger rows left (NBA only): {(df['year_id'] < MERGER_SEASON).sum():,}")
print(f"ABA team codes left: {df['team_name_abbr'].isin(ABA_TEAMS).sum()}")

Dropped 369 pre-merger ABA rows (22,453 → 22,084)
Seasons remaining: 1973-74 → 2025-26
Pre-merger rows left (NBA only): 679
ABA team codes left: 0

In [14]:
# Additional hardening for an analysis-ready dataset
# Run this notebook inside the conda environment: nba

MERGER_SEASON = "1976-77"
numeric_cols = ["age", "games", "mp", "per", "bpm", "vorp", "ws", "ws_per_48"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

before = len(df)
df = df.loc[~(df["year_id"] < MERGER_SEASON)].copy()

# Drop rows that are still incomplete or nonsensical for analysis
required_cols = ["player_name", "player_url", "team_name_abbr", "age", "games", "mp"]
df = df.loc[df[required_cols].notna().all(axis=1)].copy()
df = df.loc[(df["games"] > 0) & (df["mp"] > 0) & (df["age"].notna())].copy()

# Keep only standard-length NBA seasons and meaningful playing-time seasons
before_games = len(df)
df = df.loc[(df["games"] <= 82) & (df["games"] >= 40) & (df["mp"] >= 1000)].copy()

# Keep a stable row order for downstream analysis
# (player-season keys should be unique after earlier de-duplication)
df = df.sort_values(["player_url", "year_id"]).reset_index(drop=True)

print(f"Dropped {before - len(df):,} rows after removing pre-merger seasons, invalid records, and low/overlong seasons ({before:,} → {len(df):,})")
print(f"Seasons remaining: {df['year_id'].min()} → {df['year_id'].max()}")
print(f"Rows with remaining nulls:\n{df[numeric_cols + required_cols].isna().sum()}")
print(f"Dropped {before_games - len(df):,} rows failing the games/minutes filters")

# Optional: save the stricter cleaned dataset for later notebooks
out_path = Path("..") / "data" / "03-cleaned" / "nba_complete_clean.csv"
out_path.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(out_path, index=False)
print(f"Saved stricter cleaned dataset to: {out_path}")

Dropped 10,377 rows after removing pre-merger seasons, invalid records, and low/overlong seasons (22,084 → 11,707)
Seasons remaining: 1976-77 → 2025-26
Rows with remaining nulls:
age               0
games             0
mp                0
per               0
bpm               0
vorp              0
ws                0
ws_per_48         0
player_name       0
player_url        0
team_name_abbr    0
age               0
games             0
mp                0
dtype: int64
Dropped 9,698 rows failing the games/minutes filters
Saved stricter cleaned dataset to: ../data/03-cleaned/nba_complete_clean.csv

In [15]:
# --- Anomaly / completeness checks on cleaned df ---
metric_cols = ["per", "bpm", "vorp", "ws", "ws_per_48"]
id_cols = ["player_url", "year_id"]

qa = df.copy()
qa["season_start"] = qa["year_id"].str.slice(0, 4).astype(int)

print("=== Coverage ===")
print(f"Rows: {len(qa):,} | players: {qa['player_url'].nunique():,} | seasons: {qa['year_id'].nunique()} ({qa['year_id'].min()} → {qa['year_id'].max()})")
print(f"Nulls in key cols:\n{qa[id_cols + ['player_name', 'age', 'games', 'mp'] + metric_cols].isna().sum()}")

print("\n=== Identity / uniqueness ===")
dup_seasons = qa.duplicated(subset=id_cols, keep=False)
print(f"Duplicate player-season keys: {dup_seasons.sum()}")
names_per_url = qa.groupby("player_url")["player_name"].nunique()
urls_per_name = qa.groupby("player_name")["player_url"].nunique()
print(f"URLs with >1 display name: {(names_per_url > 1).sum()}")
print(f"Display names with >1 URL (homonyms): {(urls_per_name > 1).sum()}")
if (urls_per_name > 1).any():
    display(urls_per_name[urls_per_name > 1].sort_values(ascending=False).head(15).to_frame("n_urls"))

print("\n=== Career season gaps (missing years between first and last) ===")
# Gaps are often real (injury / overseas / G-League); flag for review.
gap_rows = []
for url, g in qa.groupby("player_url"):
    years = sorted(g["season_start"].unique())
    name = g["player_name"].iloc[0]
    for prev, curr in zip(years, years[1:]):
        hole = curr - prev - 1
        if hole > 0:
            gap_rows.append(
                {
                    "player_name": name,
                    "player_url": url,
                    "after_season": prev,
                    "before_season": curr,
                    "missing_years": hole,
                    "career_seasons": len(years),
                }
            )
gaps = pd.DataFrame(gap_rows)
print(f"Players with ≥1 gap: {gaps['player_url'].nunique() if len(gaps) else 0}")
print(f"Total gap segments: {len(gaps)}")
if len(gaps):
    display(gaps.sort_values("missing_years", ascending=False).head(15))

print("\n=== Age consistency across seasons ===")
qa = qa.sort_values(["player_url", "season_start"])
qa["age_delta"] = qa.groupby("player_url")["age"].diff()
qa["year_delta"] = qa.groupby("player_url")["season_start"].diff()
age_bad = qa[qa["year_delta"].notna() & ((qa["age_delta"] - qa["year_delta"]).abs() > 1)]
print(f"Seasons where age jump ≠ year jump (±1 tolerance): {len(age_bad)}")
if len(age_bad):
    display(age_bad[["player_name", "year_id", "age", "age_delta", "year_delta"]].head(20))

print("\n=== Playing-time sanity ===")
print(f"Rows with mp < games: {(qa['mp'] < qa['games']).sum()}")
print(f"Rows with games > 82: {(qa['games'] > 82).sum()} (ABA / 3-team seasons can exceed 82)")
print(f"Rows with games == 0: {(qa['games'] == 0).sum()}")

print("\n=== Completeness vs raw (same metric filters, before multi-team collapse) ===")
raw = pd.read_csv(DATA_PATH)
raw["player_url"] = raw["player_url"].fillna(raw["player_name"].map(missing_urls))
raw = raw.loc[~raw["team_name_abbr"].str.startswith("Did not play", na=False)].copy()
raw = raw.dropna(subset=["age"] + metric_cols)
# expected unique player-seasons if we keep nTM totals only
ntm = raw["team_name_abbr"].str.match(r"^\d+TM$", na=False)
raw["_has_ntm"] = raw.groupby(["player_url", "year_id"])["team_name_abbr"].transform(
    lambda s: s.str.match(r"^\d+TM$", na=False).any()
)
raw_expected = raw.loc[~raw["_has_ntm"] | ntm, id_cols].drop_duplicates()
raw_expected = raw_expected.drop_duplicates(subset=id_cols)

clean_keys = qa[id_cols].drop_duplicates()
missing = raw_expected.merge(clean_keys, on=id_cols, how="left", indicator=True)
missing = missing.loc[missing["_merge"] == "left_only", id_cols]
extra = clean_keys.merge(raw_expected, on=id_cols, how="left", indicator=True)
extra = extra.loc[extra["_merge"] == "left_only", id_cols]

print(f"Expected player-seasons (raw, metric-complete, nTM-collapsed): {len(raw_expected):,}")
print(f"Cleaned player-seasons: {len(clean_keys):,}")
print(f"Missing from cleaned: {len(missing)}")
print(f"Extra in cleaned: {len(extra)}")
if len(missing):
    display(missing.head(20))

=== Coverage ===
Rows: 11,707 | players: 2,105 | seasons: 50 (1976-77 → 2025-26)
Nulls in key cols:
player_url     0
year_id        0
player_name    0
age            0
games          0
mp             0
per            0
bpm            0
vorp           0
ws             0
ws_per_48      0
dtype: int64

=== Identity / uniqueness ===
Duplicate player-season keys: 0
URLs with >1 display name: 0
Display names with >1 URL (homonyms): 7

                  n_urls
player_name
Charles Jones          2
Charles Smith          2
Eddie Johnson          2
George Johnson         2
Gerald Henderson       2
Mike Dunleavy          2
Reggie Williams        2

=== Career season gaps (missing years between first and last) ===
Players with ≥1 gap: 797
Total gap segments: 1028

,player_name,player_url,after_season,before_season,missing_years,career_seasons
719,Doug Overton,https://www.basketball-reference.com/players/o...,1994,2003,8,2
297,Danté Exum,https://www.basketball-reference.com/players/e...,2016,2023,6,3
804,Sergio Rodríguez,https://www.basketball-reference.com/players/r...,2009,2016,6,3
981,Ennis Whatley,https://www.basketball-reference.com/players/w...,1986,1993,6,4
478,Anthony Johnson,https://www.basketball-reference.com/players/j...,1997,2003,5,7
581,Sidney Lowe,https://www.basketball-reference.com/players/l...,1983,1989,5,2
144,Jud Buechler,https://www.basketball-reference.com/players/b...,1992,1998,5,2
174,Anthony Carter,https://www.basketball-reference.com/players/c...,2001,2007,5,5
456,Jonathan Isaac,https://www.basketball-reference.com/players/i...,2018,2024,5,2
963,Bill Walton,https://www.basketball-reference.com/players/w...,1977,1983,5,5
624,JaVale McGee,https://www.basketball-reference.com/players/m...,2012,2018,5,7
921,Jamaal Tinsley,https://www.basketball-reference.com/players/t...,2006,2012,5,7
57,Jon Barry,https://www.basketball-reference.com/players/b...,1993,1999,5,7
351,Gerald Green,https://www.basketball-reference.com/players/g...,2006,2012,5,6
1010,Shelden Williams,https://www.basketball-reference.com/players/w...,2006,2011,4,2

=== Age consistency across seasons ===
Seasons where age jump ≠ year jump (±1 tolerance): 0

=== Playing-time sanity ===
Rows with mp < games: 0
Rows with games > 82: 0 (ABA / 3-team seasons can exceed 82)
Rows with games == 0: 0

=== Completeness vs raw (same metric filters, before multi-team collapse) ===
Expected player-seasons (raw, metric-complete, nTM-collapsed): 22,453
Cleaned player-seasons: 11,707
Missing from cleaned: 10746
Extra in cleaned: 0

                                           player_url  year_id
0   https://www.basketball-reference.com/players/a...  1990-91
1   https://www.basketball-reference.com/players/a...  1991-92
3   https://www.basketball-reference.com/players/a...  1993-94
4   https://www.basketball-reference.com/players/a...  1994-95
5   https://www.basketball-reference.com/players/a...  1973-74
6   https://www.basketball-reference.com/players/a...  1974-75
7   https://www.basketball-reference.com/players/a...  1975-76
8   https://www.basketball-reference.com/players/a...  1976-77
9   https://www.basketball-reference.com/players/a...  1977-78
10  https://www.basketball-reference.com/players/a...  1973-74
11  https://www.basketball-reference.com/players/a...  1974-75
12  https://www.basketball-reference.com/players/a...  1975-76
33  https://www.basketball-reference.com/players/a...  1997-98
34  https://www.basketball-reference.com/players/a...  2000-01
35  https://www.basketball-reference.com/players/a...  1997-98
38  https://www.basketball-reference.com/players/a...  2000-01
39  https://www.basketball-reference.com/players/a...  2001-02
40  https://www.basketball-reference.com/players/a...  2002-03
48  https://www.basketball-reference.com/players/a...  2003-04
52  https://www.basketball-reference.com/players/a...  2007-08

In [16]:
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"Seasons: {df['year_id'].nunique()} ({df['year_id'].min()} → {df['year_id'].max()})")
print(f"Players: {df['player_name'].nunique():,}")
print(f"Teams:   {df['team_name_abbr'].nunique()}")
print()

display(df.dtypes.to_frame("dtype"))
display(df.isna().sum().to_frame("nulls").assign(pct=lambda x: (x["nulls"] / len(df) * 100).round(1)))
display(df.describe())
display(df.head(10))

Shape: 11,707 rows × 12 columns
Seasons: 50 (1976-77 → 2025-26)
Players: 2,098
Teams:   45

                  dtype
player_name      object
player_url       object
year_id          object
age             float64
team_name_abbr   object
games           float64
mp              float64
per             float64
bpm             float64
vorp            float64
ws              float64
ws_per_48       float64

                nulls  pct
player_name         0  0.0
player_url          0  0.0
year_id             0  0.0
age                 0  0.0
team_name_abbr      0  0.0
games               0  0.0
mp                  0  0.0
per                 0  0.0
bpm                 0  0.0
vorp                0  0.0
ws                  0  0.0
ws_per_48           0  0.0

,age,games,mp,per,bpm,vorp,ws,ws_per_48
count,11707.000000,11707.000000,11707.000000,11707.000000,11707.000000,11707.000000,11707.000000,11707.000000
mean,26.769967,71.577091,1953.461006,15.015136,0.057555,1.197762,4.404314,0.102572
std,3.922575,10.053900,586.424224,3.970859,2.570736,1.594026,2.986191,0.051279
min,18.000000,40.000000,1000.000000,3.000000,-8.300000,-2.600000,-2.100000,-0.084000
25%,24.000000,66.000000,1461.000000,12.300000,-1.700000,0.100000,2.300000,0.068000
50%,26.000000,75.000000,1910.000000,14.600000,-0.200000,0.800000,3.800000,0.099000
75%,29.000000,80.000000,2409.000000,17.200000,1.400000,1.800000,5.900000,0.133000
max,42.000000,82.000000,3638.000000,32.800000,14.200000,12.500000,21.200000,0.323000

,player_name,player_url,year_id,age,team_name_abbr,games,mp,per,bpm,vorp,ws,ws_per_48
0,Alaa Abdelnaby,https://www.basketball-reference.com/players/a...,1992-93,24.0,2TM,75.0,1311.0,13.2,-3.9,-0.6,2.0,0.074
1,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1976-77,29.0,LAL,82.0,3016.0,27.8,9.4,8.7,17.8,0.283
2,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1977-78,30.0,LAL,62.0,2265.0,29.2,9.3,6.5,12.1,0.257
3,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1978-79,31.0,LAL,80.0,3157.0,25.5,7.6,7.7,14.4,0.219
4,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1979-80,32.0,LAL,82.0,3143.0,25.3,7.2,7.3,14.8,0.227
5,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1980-81,33.0,LAL,80.0,2976.0,25.5,6.1,6.1,14.3,0.230
6,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1981-82,34.0,LAL,76.0,2677.0,23.4,5.0,4.7,10.7,0.192
7,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1982-83,35.0,LAL,79.0,2554.0,23.6,4.5,4.2,10.9,0.205
8,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1983-84,36.0,LAL,80.0,2622.0,21.3,3.0,3.3,8.9,0.163
9,Kareem Abdul-Jabbar,https://www.basketball-reference.com/players/a...,1984-85,37.0,LAL,79.0,2630.0,22.9,5.1,4.8,11.2,0.204